@address = localhost:8080

### Root path returns 404
GET http://{{address}}/

### Health check
GET http://{{address}}/health

### Create user
POST http://{{address}}/user
content-type: application/json

{
    "email": "some@domain.net",
    "password": "test_password"
}

### Login request
POST http://{{address}}/login
content-type: application/json

{
    "email": "some@domain.net",
    "password": "test_password"
}

### Invalid login request
POST http://{{address}}/login
content-type: application/json

{
    "email": "invalid@domain.net",
    "password": "invalid"
}
