@address = localhost:8080

### Root path returns 404
GET http://{{address}}/

### Health check
GET http://{{address}}/health

### Login request
POST http://{{address}}/login
content-type: application/json

{
    "username": "test",
    "password": "test"
}
